export type ChatEvents =
  | "sync"
  | "syncing"
  | "syncError"
  | "syncUpdate"
  | "messageCreatedLDB"
  | "messageDeletedLDB"
  | "messageUpdatedLDB"
  | "conversationCreatedLDB"
  | "conversationUpdatedLDB"
  | "messageCreatedLDBError"
  | "messageDeletedLDBError"
  | "messageUpdatedLDBError"
  | "conversationCreatedLDBError"
  | "conversationUpdatedLDBError"
