export type AuthEvents =
  | "__authenticate"
  | "__onLoginComplete"
  | "__onLoginError"
  | "__onLogoutComplete"
  | "__logout"
  | "__onAccountReady"
  | "__tryRebuildAccountOnRefresh"
  | "__dismiss"
  | "auth"
  | "onAuthError"
  | "logout"
