export enum NotificationSubType {
  MAKER_CREATED_DEAL = "0",
  TAKER_ACCEPTED_DEAL = "1",
  CREATOR_THREAD_PUT_LIKE = "0",
  CREATOR_THREAD_PUT_NO_LIKE = "1",
  THREAD_HAS_NEW_REPLY = "2",
  CREATOR_THREAD_ACCEPTED_REPLY = "3",
  SOMEONE_CREATED_THREAD = "4",
  FOLLOWED_CREATED_THREAD = "5",
  SOMEONE_FOLLOWED_YOU = "0",
  SYSTEM = "0",
}
